apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: thrizer-clinician-db
  name: thrizer-clinician-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: thrizer-clinician-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/reverse-proxy: "true"
        io.kompose.service: thrizer-clinician-db
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
          image: mongo
          name: thrizer-clinician-db
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: thrizer-clinician-db-claim0
            - mountPath: /docker-entrypoint-initdb.d/mongo-init.js
              name: thrizer-clinician-db-claim1
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      hostname: thrizer-clinician-db
      restartPolicy: Always
      volumes:
        - name: thrizer-clinician-db-claim0
          persistentVolumeClaim:
            claimName: thrizer-clinician-db-claim0
        - name: thrizer-clinician-db-claim1
          persistentVolumeClaim:
            claimName: thrizer-clinician-db-claim1
status: {}
